In [1]:
import pandas as pd

df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")

df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

# Project 1: Data Cleaning and Transformation

This project focuses on cleaning and preparing a used car dataset using Python and Pandas.

In [2]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [4]:
df.columns

Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')

In [7]:
df.fillna("NO ESPECIFICADO", inplace=True)

The dataset was checked for missing values, and none were found.

In [12]:
df = df.applymap(lambda x: x.upper() if isinstance(x, str) else x)

/tmp/ipykernel_5166/197485208.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.upper() if isinstance(x, str) else x)

In [13]:
df = df.map(lambda x: x.upper() if isinstance(x, str) else x)

In [8]:
df.duplicated().sum()

np.int64(763)

In [10]:
df.drop_duplicates(inplace=True)

In [11]:
df.duplicated().sum()

np.int64(0)

In [14]:
df["brand"] = df["name"].apply(lambda x: x.split()[0])

df[["name", "brand"]].head()

                       name    brand
0             MARUTI 800 AC   MARUTI
1  MARUTI WAGON R LXI MINOR   MARUTI
2      HYUNDAI VERNA 1.6 SX  HYUNDAI
3    DATSUN REDIGO T OPTION   DATSUN
4     HONDA AMAZE VX I-DTEC    HONDA

In [15]:
df.shape

(3577, 9)

In [17]:
df.to_csv("cleaned_car_data.csv", index=False)